### ISSUE TITLE
[RFC] Add Stack component

### ISSUE THREAD

**Issue by afontcu** [holaluz/margarita#268]
Superseeds #251 

Related to https://github.com/holaluz/margarita/issues/256

---

I've explored some simple API for a Stack component that handles spacing in a composable way, and this is what I came up with. Please do only **focus on layout**, not styling!! :)

## An example

Original:

![image](https://user-images.githubusercontent.com/9197791/90170059-c0a81180-dd9f-11ea-866f-9d4c3f953462.png)

Result:

![image](https://user-images.githubusercontent.com/9197791/90170293-1f6d8b00-dda0-11ea-814a-a124326b3de8.png)

(there's just some stylistic CSS, but the important bits is that different elements have different spaces between them – all by composing the same Stack component)

the code for the image above:

```vue
<template>
    <stack space="medium">
      <stack align="center">
        <h1>acceso a ventas</h1>
      </stack>
      <stack space="small">
        <label>email</label>
        <input />
        <label>contraseña</label>
        <input />
        <p>recuperar mi contraseña</p>
        <button>entrar</button>
      </stack>
    </stack>
</template>
```

---

## Another example

Original: 
![image](https://user-images.githubusercontent.com/9197791/90170145-dfa6a380-dd9f-11ea-8d65-fa72a701dea4.png)

Result:

![image](https://user-images.githubusercontent.com/9197791/90170623-9a36a600-dda0-11ea-849a-dd80e5b19c5b.png)

Snippet:

```vue
<template>
  <stack space="medium" align="center">
    <stack space="small">
      <h1>introduce tu dirección CUPS</h1>
      <p>esta información es necesaria porque blablabla</p>
    </stack>

    <!-- Same as the original proposal: This one should have a container that aligns right -->
    <p style="align-self: end;">direccion / cups toggle</p>
    <stack space="small">
      <cups-input />
    </stack>
    <button>descubre tu tarifa</button>
    <p>volver atrás</p>
  </stack>
</template>
```

Notice how the spacing is different between the title and the subtitle, and the rest of elements from the form.

## Proof of Concept implementation

```vue
<template>
  <component :is="component" :style="style" class="stack">
    <slot />
  </component>
</template>

<script>
export default {
  name: 'Stack',

  props: {
    space: {
      type: String,
      required: true,
      validator: (p) => ['small', 'medium', 'large'].includes(p),
    },

    align: {
      type: String,
      default: '',
      validator: (p) => !p || ['start', 'center', 'end'].includes(p),
    },

    component: {
      type: String,
      default: 'div', // this way we could handle lists and so
    },
  },

  computed: {
    // to be replaced with a proper implementation of DS tokens
    spaceValue() {
      if (this.space === 'small') return '0.5rem'
      if (this.space === 'medium') return '2rem'
      return '3rem'
    },

    style() {
      return {
        '--space': this.spaceValue,
        '--align-items': this.align,
      }
    },
  },
}
</script>

<style scoped>
.stack {
  display: flex;
  flex-direction: column;
  align-items: var(--align-items);
  gap: var(--space);
}
</style>
```

Remember that this is just a prototype to see how well it handles common scenarios 😉 

---

Thoughts? Would this solve the scenarios you face on a daily basis? What would you miss from it?

**Comment by afontcu** [comment]
Here's a Codesandbox to play with the POC implementation of Stack: https://codesandbox.io/s/agitated-sun-uw4jf

**Comment by Samitier** [comment]
Great job! Some doubts I have:

 - Who controls the width of the children? For example: what happens if I want a full width stack? Should I specify a `width: 100%` in every children? Should I specify it in the `align` prop? IE: `align: fill`?
 - Who controls the horizontal padding/margin of an element of a stack?
 - I am super worried of making our templates an unreadable clutter of nested stacks because every design I've seen in our pages have different separations for each child. Are we sure we want to discard passing the separations explicitly? IE: `space="small|small|big"`? We could make it responsive too in combination with the `$layout` [responsive plugin](https://github.com/holaluz/margarita/issues/266): `:space="$layout.mobile ? 'small' : 'small|big|big'"`.

**Comment by afontcu** [comment]
Thanks for the feedback!

> Who controls the width of the children? For example: what happens if I want a full width stack? Should I specify a width: 100% in every children? Should I specify it in the align prop? IE: align: fill?

> Who controls the horizontal padding/margin of an element of a stack?

_(I've merge both questions because I think their answers are quite related)_

Not the Stack, definitely 😛 since it only handles vertical spacing, as its name suggests. We might need a component to handle horizontal spacing, too (I think I called it `ma-inline` yesterday during the call, but that was just the first name that came to my mind). Or even two or more (we might want to define columns as well!).

As a rule of thumb, the UI components should be "liquid" enough and fill the whole available horizontal spacing unless specified otherwise.


> I am super worried of making our templates an unreadable clutter of nested stacks because every design I've seen in our pages have different separations for each child. 

Legit! Could you share one of those designs, and see what we can come up with? I feel that the minute we extract the parts of these layouts into specific components we might be able to reduce the cluttering to some extent. Also, design people should help us here 😉 

Moreover, for really complex and tricky designs we can always rely on tools such as CSS Grid (while using the same spacing tokens as Layout components)!


> Are we sure we want to discard passing the separations explicitly? IE: space="small|small|big"? We could make it responsive too in combination with the $layout responsive plugin: :space="$layout.mobile ? 'small' : 'small|big|big'".

This would kind of defeat the purpose of composability, right? 

Thinking in terms of DX and ergonomics, I do believe that "hiding" the plugin implementation behind Stack (and all other Layout components! Hidden, Inline… you name it) is beneficial in the long run – not for us, but for everyone building UIs in Holaluz.

Not sure if there's a benefit in exposing these internals over composing a few Stacks (honestly wondering xD)

Also: what about appearing/disappearing elements? A lot of logic would be involved in parent, defeating the purpose of the Layout component itself. This is where composability shines.

---

thanks for your thoughts! Let's keep exploring 😉

**Comment by Samitier** [comment]
> As a rule of thumb, the UI components should be "liquid" enough and fill the whole available horizontal spacing unless specified otherwise.

So always full-width unless `align` is specified? What if we want `full-width` with align (text-align) right? For example this:

![image](https://user-images.githubusercontent.com/4160121/91832766-1c9ae300-ec46-11ea-8007-368faa195d34.png)

> Could you share one of those designs, and see what we can come up with?

Yes, for example this: 

![image](https://user-images.githubusercontent.com/4160121/91831835-d5f8b900-ec44-11ea-8345-e818aa052c95.png)

Agreed that with components we will reduce the clutter, but we will still have hundreds of nested divs in the html, we will only "hide" it 😂 .

> This would kind of defeat the purpose of composability, right?

Hmm yeah. But I kinda see a layout a composite of `<grid> <column> <stack>`. But when we have to nest `stacks` with `stacks` kinda feels like a smell because just by looking at an UI its very hard to decide when something is a composite of stacks (compared for example with a composite of `<column>`, where it's clearly visible).

> Also: what about appearing/disappearing elements?

Yeah...we commented that in the other RFC. Creisi idea: what about something like this?
Example of `Introduce tu dirección`:

```vue
<stack
   gap="medium"
   gap-title="small"
   gap-cupsInput="small"
   align="center"
   align-selectorCups="right"
>
    <template v-slot:title>
      <h1>introduce tu dirección CUPS</h1>
      <p>esta información es necesaria porque blablabla</p>
    </template>

    <template v-slot:selectorCups>
        <p>direccion / cups toggle</p>
    </template>

    <template v-slot:cupsInput>
      <cups-input />
    </template>

    <template v-slot:buttons>
        <button>descubre tu tarifa</button>
        <p>volver atrás</p>
    </template>
</stack>
```
Then we get a stacked layout with only one stack. Everything that is "piled" will have the same parent in a view regardless of align or gaps. Just a creisi idea to brainstorm.
