### ISSUE TITLE
[RFC] MaText component

### ISSUE THREAD

**Issue by edufarre** [holaluz/margarita#296]
- Start Date: 09/12/2020
- Target Minor Version: 6.2.0
- Related to: #255
- Implementation PR: #295

# Summary

Add the typography rules from the Design System to a `MaText` Margarita component.

# Basic example

Using component slot:
```vue
<ma-text size="xsmall" tag="p">
  Hello everybody
</ma-text>
```
Using `v-text` directive:
```vue
<ma-text size="xsmall" tag="p" v-text="'Hello everybody'"/>
```

Using our `v-markdown` directive:
```vue
<ma-text size="xsmall" tag="p" v-markdown="'Hello **everybody**'">
```

# Motivation

This issue aims to resolve the inconsistency between font styles across the different device's screen sizes .

# Component API

The component could have to props; `tag` and `size`. Where `tag` could be one of the text tags that we use the most:
```js
tag: 'p', 'span', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6' // span as default?
```
and `size` one of the agreed size names on the DS:
```js
size: 'xsmall', 'small', 'base', 'medium', 'large', 'xlarge', 'xxlarge',  'xxxlarge' // base as default?
```

# Alternatives

We could use utility classes instead of a component as already commented on the related issue on the first section.

```vue
<span class="xsmall">
  Hello everybody
</span>
```

# Adoption strategy

This is not a breaking change, thus allowing us start using this component at the same time that replacing the different text tags by this new implemented component.

# Unresolved questions

### How should be approach the line height's negative margin?
* https://medium.com/eightshapes-llc/cropping-away-negative-impacts-of-line-height-84d744e016ce
* https://medium.com/eightshapes-llc/space-in-design-systems-188bcbae0d62#9406

A good option here would be using the suggested tool in order to compute the negative margins that a speceific `line-height` should have. [Link to text crop tool](http://text-crop.eightshapes.com/). Once knowing them we could add these to our project's tokens, thus tackling the targeted issue.

### What should we do with the different font families?
* Shall we add `Canela` font family as well to the project?
If so, we should bear in mind that that would require a new component's `prop`, which allowed values would be:
```js
font: 'Ciutadella', 'Canela', 'Arial' // Ciutadella as default?
```
finally being something like:
```vue
<ma-text size="xsmall" tag="p" font="Canela">
  Hello everybody
</ma-text>
```

**Comment by afontcu** [comment]
Looks great!


> How should be approach the line height's negative margin?

I strongly believe the component should handle this. Otherwise, layout components lose power, as they won't be able to properly translate mock-ups into real, live UIs.

> What should we do with the different font families?

I'd say so! It'd be great if we could count on the component to handle available font-families


> We could use utility classes instead of a component as already commented on the related issue on the first section

This is an interesting take. If we aim for providing support to any UI (regardless of using Vue or not), this approach would make sense. We could style HTML elements with sensible defaults (based on HTML elements and viewport), and provide utility classes for specific cases.

---

Here are some thoughts on additional issues I find interesting:

* Should the component also handle text color?
* Should the component also handle text variations (bold, italics…)?
* What should be the relationship between MaText and responsive, fluid typography? This is something the design system takes into account, and I'm not quite sure how it should be translated into code.
* What should be the relationship between MaText and other text-based nodes from other components such as `<label>` in MaTextField?
* Also, I still find a bit awkward that we have both `base` and `medium` font sizes, because in other components `medium` acts as the default (base?) value.

**Comment by Samitier** [comment]
+1 to handle font families and bold/italic

I think color is trickier since we won't have the DS colors in the js (unless we add a way to access them from js). Ironically, managing the colors is easier with the utility classes 😂 

Also: why don't we use this component to integrate i18n into the mix. That is something like:

```vue
// copies
{ foo: { bar: "Hello world " } }

// Template
<ma-text text="foo.bar" />

// Output
<div class="ma-font">Hello world</div>
```

Or even as a wrapper of the `<i18n>` component that we use almost everywhere, since we won't be able to use it in conjuntion with this. For example:

```
// How do we use ma-text here?
<i18n path="foo" tag="p" />
```

And we can even integrate this with markdown too, since all markdown text need a `white-space: pre-wrap` for endlines to work and I'm tired of writing that css everywhere 😂 

```vue
// copies (yml)
foo: |+
    Paragraph 1
 
    Paragraph 2

// Template
<ma-text text="foo" />

// Output
<div class="ma-font">
  Paragraph 1

  Paragraph 2
</div>
```
Main advantage of this: we will manage internationalization the same way everywhere (no copies without internationalization, no i18n components that should be markdown like bolds and links, avoid passing copies as parameters in components, no more difference between markdown and non markdown, etc). 

We also don't need the dependency in margarita since we can easily mock it (`$t: key => key`) . 

I dunno it seems like a good idea "in paper" but I would like to hear your opinion 😂

**Comment by afontcu** [comment]
> I think color is trickier since we won't have the DS colors in the js (unless we add a way to access them from js)

I think this could be easily solved with CSS custom props 😛  which would also help to pave the way to remove SCSS from our tooling 😬 

### Regarding i18n

My main gripe here is the mismatch between "MaText handles translations" and "MaTextField, MaModal, and any other text-containing component does not" (the same fear I mentioned in my first post). This could be solved by using `MaText` inside those components, though.

Also, vue-i18n offers a shitton of features, of which we're only scratching the surface. I'd hate to see how we miss some of them in our quest to save a few keystrokes. 

>// How do we use ma-text here?
<i18n path="foo" tag="p" />

AFAICT, i18n also accepts receiving `:tag="false"`, which inserts the root node without wrapping elements. It'd be great to check if the prop accepts a component, too 🤔  `<i18n path="foo" tag="ma-text">`

---

**Comment by icurdu** [comment]
> Also, I still find it a bit awkward that we have both base and medium font sizes because in other components medium acts as the default (base?) value.

Totally agree. I think we should change the names in order to have the same naming structure (where Medium means base/default). This will give us more consistency. On the other hand, we will have `xxxxlarge` font class 😂 . 

> Should the component also handle text color?

I think so! In my opinion, the component should accept any of our DS colors.

**Comment by afontcu** [comment]
> Totally agree. I think we should change the names in order to have the same naming structure (where Medium means base/default). This will give us more consistency. On the other hand, we will have `xxxxlarge` font class 😂 .

You might have already thought of that, but I gotta ask 😂: Have you considered the possibility of having one less font-size option? 😬 

> In my opinion, the component should accept any of our DS colors.

Cool! 

We could even accept to props: `color` for the main color, and `tone` for the "variation" (light, dark). <-- this is just something I mentioned, other solutions may apply!

**Comment by edufarre** [comment]
Since we change the way we handle the DS tokens, I created a [new PR](https://github.com/holaluz/margarita/pull/327) that aims to implement the agreed API. There are just a couple of things pending:
* How shall we handle the negative margin? 
As previously commented, there is an online tool that helps as computing it, shall we use it and store its values per each `font-size`?
> How should be approaching the line height's negative margin? 
> https://medium.com/eightshapes-llc/cropping-away-negative-impacts-of-line-height-84d744e016ce
> https://medium.com/eightshapes-llc/space-in-design-systems-188bcbae0d62#9406

*  What about the `font-family`?
Right now `margarita` only contains the `Ciutadella` font. Should we add `Canela` as well to the project, and then set `Arial` as the fallback one?
```js
font: 'Ciutadella', 'Canela', 'Arial' // Ciutadella as default
```

**Comment by afontcu** [comment]
> What about the `font-family`?

That's a legit concern. Question: are we gonna use font families everywhere, or are they restricted to Headings? If that's the case, I suggest we create a MaHeading component that handles it.

The answer to this question might affect the way we handle negative margin, too. btw, I raised the negative margin issue – we might want to ignore it if it's not a real problem!

**Comment by afontcu** [comment]
> That's a legit concern. Question: are we gonna use font families everywhere, or are they restricted to Headings? If that's the case, I suggest we create a MaHeading component that handles it.

Actually this would reduce the amount of possibilities when it comes to size, too, right? 🤔 maybe it's worth discussing…

**Comment by edufarre** [comment]
> > That's a legit concern. Question: are we gonna use font families everywhere, or are they restricted to Headings? If that's the case, I suggest we create a MaHeading component that handles it.

 I believe we could have a heading with `font-family: Ciutadella | Canela`. What I mean by this, is that we could have all the discussed fonts across all different text HTML tags.

> Actually this would reduce the number of possibilities when it comes to size, too, right? 🤔 maybe it's worth discussing…

Honestly, I wouldn't bet on it, I'd probably ask the 🚦 team. Because if we have 'X' use cases for the font, we might be able to set a `capheight` and a `baseline` values, thus having them as DS tokens in order to use the font properly in no matter which project.
