### ISSUE TITLE
How should we treat and handle shadows?

### ISSUE THREAD

**Issue by edufarre** [holaluz/margarita#305]
## Current approach

We have them implemented as scss variables:
```scss
$shadow-light: rgba(0, 0, 0, 0.027451);
$shadow-medium: rgba(0, 0, 0, 0.0980392);
$shadow-dark: rgba(0, 0, 0, 0.498);
```

## Suggested approach (by @Samitier ) commented on [this PR](https://github.com/holaluz/margarita/pull/302#discussion_r545636122)

They are not actually shadows per se, just blacks with opacity. Maybe we should just unify the entire box-shadow in a variable or treat the shadow color as just another color.

I mean this as box shadow:
```scss
$shadow-light: npx npx npx rgba(0, 0, 0, 0.027451);
```
Or this as color:
```scss
shadow-base: rgba(0, 0, 0, 0.027451);
shadow-light: ...
shadow-dark: ...
```

**Comment by icurdu** [comment]
Most of our shadows are black with opacity, but there's one type of shadow that we use for images on the homepage that has another color, and we want to use it more often. 

After some discussion in design, we have an [initial approach to shadows](https://www.figma.com/file/7RhweKibaUnxX6WYBl7zKW/Design-System-Beta?node-id=1739%3A0), based on where are these used. We wanted to have opacity and color as variables, but maybe it's better to have strict values. 

As I'm writing this, one question came out: Should we name the shadows following the clothing sizing convention?

**Comment by afontcu** [comment]
> Should we name the shadows following the clothing sizing convention

As far as I know (correct me if I'm wrong) shadows are used as "layers" of depth. With that in mind, I'm not entirely sure that naming shadows as clothing sizes would convey that meaning, but I'm also unable to provide an alternative 😂

**Comment by edufarre** [comment]
> As I'm writing this, one question came out: Should we name the shadows following the clothing sizing convention?

I would not use 'clothe sizing' nomenclature in this case, that would be weird when talking about shadows, isn't it?

I believe we should use the same approach as our DS colors:
```ts
shadowTypes: 'darker' | 'dark' | 'base' | 'light' | 'lighter' 
```

**Comment by Samitier** [comment]
Maybe a quick search through our repositories could tell if our shadows are consistent and need to be a variable. For example:

In dry we have more or less 9 different shadows (but I think that a lot of them are the same shadow written differently). The only shadows that are truly unique are white shadows overlying images and the brown shadow that @icurdu says.

In maitai we have 5 different shadows, but I'm 100% sure they all could be the same because they are all the same color and should have the same "depth" in the UI.

So for me, all in in standarizing the full box-shadow. For the nomenclature, what about:

`shadow-size-color`

Size: the "depth" of the shadow (the Z axis) in shirt size.
Color: the base color of the shadow.

So for example:
```
$shadow-xs-black: 0px 2px 12px rgba(0, 0, 0, 0.15);
$shadow-xs-black: 0px 2px 17px rgba(0, 0, 0, 0.15);
etc.
```
And about the X and Y coords of a box shadow, @icurdu correct me if I'm wrong but I think it's extremely weird for a UI having elements that drop shadows from different angles, like there were different light sources in the scene, so IMHO X and Y should always be consistent regardless of the Z and the color.

**Comment by afontcu** [comment]
I'll go ahead and ask another question: Do we need shadows as a global token? Could we simply provide the right UI abstractions (MaModal, MaCard, MaTooltip, Ma…) so that we wouldn't have to expose standalone shadows? 


That being said, if we need to do so, I would find a naming that help us understand that shadows are used to create layers of depth. I would keep it simple:

```css
--shadow-depth-1: whatever;
--shadow-depth-2: whatever;
--shadow-depth-3: whatever;
```

or similar

**Comment by edufarre** [comment]
I am 100% about not exposing the standalone shadows. As far as I know, we normally use them in order to apply some box-shadows (at least on `negroni`) to the `div` elements. And this could be entirely done by a proper `ma-card` element. 😅 

However, I do not see any harm in exposing them, while not being certain about their usage across our different projects.

**Comment by afontcu** [comment]
I 100% agree that a lot of use cases would be handled directly in Margarita, mostly because shadows are related to UI components, and Margarita provide those. 

That being said, Margarita can't cover each scenario, so we might still need to provide shadow tokens externally 🤔

**Comment by afontcu** [comment]
Fixed (somewhat) in https://github.com/holaluz/margarita/pull/430

Please feel free to reopen if any other need arises
