### ISSUE TITLE
MaModal is not responsive and outlines links

### ISSUE THREAD

**Issue by Samitier** [holaluz/margarita#366]
MaModal is not responsive for mobile (or screens with a small height):

![image](https://user-images.githubusercontent.com/4160121/110504866-e14e0500-80fd-11eb-9838-6e73e10a84ce.png)

And the focus trap we implemented focuses on links and gives them an outline when you open the modal, which imho is pretty weird.

**Comment by afontcu** [comment]
> And the focus trap we implemented focuses on links and gives them an outline when you open the modal, which imho is pretty weird.

That's the expected behavior for a Modal [given the spec](https://www.w3.org/TR/wai-aria-practices-1.2/#keyboard-interaction-7), to focus on the first focusable element of its content 🤔 

> When a dialog opens, focus moves to an element inside the dialog. See notes below regarding initial focus placement.

 
![image](https://user-images.githubusercontent.com/9197791/110598488-18fe9080-8182-11eb-874a-5d23d74cdfb7.png)

**Comment by Samitier** [comment]
Yeah, we will make the outline CSS less intrusive in maitai/dry and that's it.

**Comment by afontcu** [comment]
> Yeah, we will make the anchor's outline CSS less intrusive in maitai/dry and that's it.

That sounds reasonable 👍 we could also think about letting consumer to define which element has the initial focus (to make it able to fulfill points 3, 4, and 5 of screenshot above).
