### ISSUE TITLE
MaText is breaking SSR builds and CSS implementations

### ISSUE THREAD

**Issue by Samitier** [holaluz/margarita#372]
Hello,

MaText is not "SSR friendly". We can't use any component of margarita that has a MaText inside:

![image](https://user-images.githubusercontent.com/4160121/110961342-fcb04e80-834f-11eb-9287-5eca01b89714.png)

Not exactly sure why should a text field change on ssr render tho.

Also, currently MaText applies all its styles inline. This breaks some of our CSS. For example, in Kalimotxo we have a MaTextField that should have a white label. This now breaks:

![image](https://user-images.githubusercontent.com/4160121/110961714-62043f80-8350-11eb-9d5b-b6c5becbb8f5.png)

What should we do here? MaTextField should give the option to change the label color? Can't this style be set by a class instead of being inline?

**Comment by Samitier** [comment]
Wild guess, but maybe making MaText functional fixes the SSR issue?

**Comment by afontcu** [comment]
is it due to CSS custom props? 🤔

**Comment by edufarre** [comment]
Do you guys know if there is a way we could check/test these things before we get to use them across our different projects?

**Comment by afontcu** [comment]
> We can't use any component of margarita that has a MaText inside

Could we try something similar to https://github.com/holaluz/margarita/pull/376, see what happens?

> in Kalimotxo we have a MaTextField that should have a white label

The question here is: is this a valid use case that our DS should cover? If so, what elements should be allowed to be "white"? 


If this becomes a common scenario in several of our compoentns, we might want to create some sort of "provider" that would let our components know they are in a _dark mode_.

React [would handle it](https://reactjs.org/docs/context.html) this way:

```js
<ColorProvider type="dark">
  <MaText>blablabla</MaText>
</ColorProvider>
```

that would automatically change the MaText appearance (instead of adding yet another prop value). Not sure how to do that in Vue, probably using provide/inject.
