### ISSUE TITLE
MaText does not handle vertical cropping properly

### ISSUE THREAD

**Issue by afontcu** [holaluz/margarita#379]
Given the following snippet:

```vue
<ma-text>I'M a text</ma-text>
<ma-text>I'M a text</ma-text>
```

this is the current result:

![Captura de Pantalla 2021-03-22 a les 10 32 35](https://user-images.githubusercontent.com/9197791/111969111-2f99d580-8afa-11eb-87c6-09e530c8306b.png)

whereas this is what we should expect:

![image](https://user-images.githubusercontent.com/9197791/111969340-6a9c0900-8afa-11eb-92d3-05269e2a8907.png)

**Comment by Samitier** [comment]
related to this:

a ma-text inside a ma-modal will always make it overflow (due to the negative margin):

![image](https://user-images.githubusercontent.com/4160121/112502574-7aca1780-8d8a-11eb-88ff-e148c93664e0.png)

Also related to this: it's impossible to center a ma-text vertically, because the vertical cropping is not applied correctly. You can see it with a ma-option, the vertical align is a bit off:

![image](https://user-images.githubusercontent.com/4160121/112502458-60903980-8d8a-11eb-996e-280e0929b950.png)
