### ISSUE TITLE
Ma Heading should have align prop too (as Ma Text)? 

### ISSUE THREAD

**Issue by carlotamolintr** [holaluz/margarita#403]
We added align prop on Ma-Text but this wasn't added to MaHeading. Do you thing that this will be useful?

**Comment by sergigraciaj** [comment]
I'm ok with that 👍 
Although I think component's api should not be open. For me the api should follow the designs guidelines as much as possible. For example if titles would never be aligned to right (because of design stuff), we should add a validator to the prop so 'right' is not an option.
This way the consumers don't have to think if right align is a valid design option.
This opinion is not just about this proposal but for every component.

**Comment by carlotamolintr** [comment]
https://github.com/holaluz/margarita/pull/420

**Comment by edufarre** [comment]
> Although I think component's api should not be open. For me the api should follow the designs guidelines as much as possible. For example if titles would never be aligned to right (because of design stuff), we should add a validator to the prop so 'right' is not an option.

I believe this might be out of scope for this PR. However, I would add it as a topic for the next Design System meeting, because we should align the component's API with the design team
