### ISSUE TITLE
MaModal showing scroll (when should not)

### ISSUE THREAD

**Issue by carlotamolintr** [holaluz/margarita#404]
MaModal is showing an scroll in some cases that should not:

Can I increase padding top+bottom in modal-content class to fix this?

![image (1)](https://user-images.githubusercontent.com/51370533/115723881-b7386580-a380-11eb-93f2-f61f8133100f.png)

**Comment by afontcu** [comment]
> Can I add more padding in modal-content class to fix this?

Sure! That'd probably fix the issue, but why is it happening? Is it due to MaText's line-height crop? We should understand _why_ this is happening to prevent scroll from appearing in other random places ;)

**Comment by carlotamolintr** [comment]
I guess is because the input checkbox doesn't fit. Please see the images below:
<img width="937" alt="Captura de pantalla 2021-04-23 a las 15 45 37" src="https://user-images.githubusercontent.com/51370533/115880875-7a857080-a44b-11eb-9aab-d42cdfaf6d4c.png">
<img width="664" alt="Captura de pantalla 2021-04-23 a las 15 45 55" src="https://user-images.githubusercontent.com/51370533/115880880-7bb69d80-a44b-11eb-8b0a-83390045ca44.png">

**Comment by afontcu** [comment]
I see! Then I guess the question is why is the MaCheckbox not filling all the required vertical space to be rendered. Looks like a Checkbox issue (that we happened to discover through Modal), not the other way around!

**Comment by Samitier** [comment]
This is because ma-text vertical cropping. More specifically, its negative margin bottom. An element with negative margin bottom inside an overflow:auto, somehow makes the overflow auto think there is a vertical overflow.

I briefly mentioned here: https://github.com/holaluz/margarita/issues/379#issuecomment-806988909

I can't think of an easy way to fix it, but this same bug its happening in sumatutejado, maitai and dry-martini and will happen to any modal with a ma-text inside of it.

**Comment by Samitier** [comment]
fixed in #476
