### ISSUE TITLE
[MaAlert] Vertical align by default

### ISSUE THREAD

**Issue by ferbg** [holaluz/margarita#577]
Since v14.1.3, MaAlert component adds the following class:
`alert--${centeringClass}`
where centeringClass is a computed:
```
    centeringClass(): string {
      return (this.title === '' && this.title !== '') ||
        (this.title !== '' && this.text === '')
        ? 'middle'
        : 'default'
    },

```
Due to this feature, we have detected a change in several alerts, for example:

![image](https://user-images.githubusercontent.com/7702476/182601037-7f0277f2-87de-4cff-ab21-04daeaa55a34.png)

Because we are using the _**default slot**_ instead of the _**text**_ property.

To achieve the previous behaviour I could fill the _text_ property with a random value that would be overwritten by the use of the slot, but it's an ugly workaround.
![image](https://user-images.githubusercontent.com/7702476/182602447-b4f60f43-625e-4bc5-9002-0615e5ae71a1.png)

**Also**, the first part of the conditional has a bug, it seems that:
`(this.title === '' && this.title !== '')`
should be:
`(this.title === '' && this.text !== '')`

**Comment by SpykeRel04D** [comment]
This was implemented due to "fix" the bug that was occurring when you had an Alert without title or without text -> one line (It looked weird and uncentered).

But as you have said, we weren't enough carefull to check for the slots :| (basically, we didn't look at the whole code and didn't know that we were able to use them).

So, the logic is -> **The icon should be always be at top.**

We should try the code, but I think this should fix it: 

`centeringClass(): string {
      return (!this.$slots?.default?.length && this.title === '' && this.text !== '') ||
        (!this.$slots?.default?.length && this.title !== '' && this.text === '')
        ? 'middle'
        : 'default'
    },`
